version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/elixir:1.4.2
    working_directory: /home/circleci/tmp
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: code-{{ checksum ".circle-sha" }}
          paths:
            - ~/tmp


workflows:
  version: 2
  checkout_get-deps_compile:
    jobs:
      - checkout_code
