version: 2
jobs:
   build:
     working_directory: ~/tmp
     docker:
       - image: circleci/elixir:1.4.2
     steps:
       - checkout
       - run: mix local.hex --force
       - run: mix local.rebar --force

       - run:
           name: Restore Dependencies
           command:  mix deps.get
       - run:
           name: Running Tests
           command: mix test
       - run:
            name: Build Release
            command: MIX_ENV=prod mix release --env=prod
       - run:
            name: find path
            command: pwd
       - run:
           name: list dir
           command: ls -ltr

       - store_artifacts:
          path: ~/tmp/_build/prod/rel/programming_quotes/releases/0.0.1/programming_quotes.tar.gz
          destination: programming_quotes.tar.gz
