version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/elixir:1.4.2
    working_directory: /home/circleci/tmp
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: code-{{ checksum ".circle-sha" }}
          paths:
            - ~/tmp

  get_dependencies:
    docker:
      - image: circleci/elixir:1.4.2
    working_directory: /home/circleci/tmp
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - code-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - deps-{{ checksum "mix.lock" }}
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run:
          name: Restore Dependencies
          command:  mix deps.get
      - save_cache:
          key: deps-{{ checksum "mix.lock" }}
          paths:
            - ~/tmp/deps
            - ~/.mix

  compile_code:
    docker:
      - image: circleci/elixir:1.4.2
    working_directory: /home/circleci/tmp
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - code-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - deps-{{ checksum "mix.lock" }}
      - run:
          name: Compile Code
          command: MIX_ENV=prod mix compile
      - save_cache:
          key: build-{{ checksum ".circle-sha" }}
          paths:
            - ~/tmp/_build
  run_tests:
    docker:
      - image: circleci/elixir:1.4.2
    working_directory: /home/circleci/tmp
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - code-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - deps-{{ checksum "mix.lock" }}
      - restore_cache:
          keys:
            - build-{{ checksum .circle.sha" }}
      - run:
          name: Run
          command: mix test

  health_metrics:
    docker:
      - image: circleci/elixir:1.4.2
    working_directory: /home/circleci/tmp
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - code-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - deps-{{ checksum "mix.lock" }}
      - restore_cache:
          keys:
            - build-{{ checksum ".circle.sha" }}
      - run:
          name: Code Coverage
          command: mix coveralls.html
      - store_artifacts:
            path: ~/tmp/cover/excoveralls.html
            destination: code-coverage.html

workflows:
  version: 2
  checkout_get-deps_compile_test:
    jobs:
      - checkout_code
      - get_dependencies:
          requires:
            - checkout_code
      - compile_code:
          requires:
            - get_dependencies
      - run_tests:
          requires:
            - get_dependencies
      - health_metrics:
          requires:
            - get_dependencies
