version: 2
jobs:
   build:
     working_directory: /home/circleci/tmp
     docker:
       - image: circleci/elixir:1.4.2
         environment:
           MIX_ENV: test
     steps:
       - checkout
       - run: mix local.hex --force
       - run: mix local.rebar --force
       - run:
           name: Restore Dependencies
           command:  mix deps.get
       - run:
           name: Compile
           command: mix compile
       - run:
          name: Debug Workspace
          command: |
            pwd
            ls -lta /home/circleci
            ls -lha /home/circleci/tmp
       - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: /home/circleci
          # Must be relative path from root
          paths:
            - tmp

   test:
     docker:
       - image: circleci/elixir:1.4.2
     steps:
       - attach_workspace:
          at: /home/circleci/
       - run:
           name: Debug Workspace
           command: |
            pwd
            ls -lta /home/circleci
            ls -lha /home/circleci/tmp
       working_directory: /home/circleci/tmp
       - run:
           name: Running Tests
           command: mix test
       - run:
           name: Generate Coverage
           command: mix coveralls.html
       - run:
            name: Build Release
            command: MIX_ENV=prod mix release --env=prod
       - store_artifacts:
            path: ~/tmp/_build/prod/rel/programming_quotes/releases/0.0.1/programming_quotes.tar.gz
            destination: programming_quotes.tar.gz
       - store_artifacts:
            path: ~/tmp/cover/excoveralls.html
            destination: coverage.html

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
