version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/elixir:1.4.2
    working_directory: /home/circleci/tmp
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: code-{{ checksum ".circle-sha" }}
          paths:
            - ~/tmp


  get_dependencies:
    docker:
      - image: circleci/elixir:1.4.2
    working_directory: /home/circleci/tmp
    steps:
       - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
       #restore source code cache
      - restore_cache:
          keys:
            - code-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - deps-{{ checksum "mix.lock" }}
       - run: mix local.hex --force
       - run: mix local.rebar --force
       - run:
           name: Restore Dependencies
           command:  mix deps.get
       - save_cache:
          key: deps-{{ checksum "mix.lock" }}
          paths:
            - ~/tmp/deps
            - ~/.mix

   compile_code:
     docker:
      - image: circleci/elixir:1.4.2
    working_directory: /home/circleci/tmp
    steps:
       - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
       #restore source code cache
      - restore_cache:
          keys:
            - code-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - deps-{{ checksum "mix.lock" }}
      - run:
          name: Running Tests
          command: MIX_ENV=test mix compile
       - save_cache:
          key: build-{{ checksum ".circle-sha" }}
          paths:
            - ~/tmp/_build




workflows:
  version: 2
  checkout_get-deps_compile:
    jobs:
      - checkout_code
      - get_dependencies:
        requires:
          - checkout_code
      - compile_code:
        requires:
          - get_dependencies
